config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => "registrations"}

  root to: 'pages#home'

  get 'profile', to: "users#show", as: "profile"

  resources :mountains, only: [:index]

  resources :experiences, only: [:show, :index, :new, :create] do
    resources :bookings, only: [:new, :create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :experience
  belongs_to :user
end

app/models/experience.rb
class Experience < ApplicationRecord

  belongs_to :mountain
  belongs_to :user

  validates :name, presence: true
  validates :description, presence: true
  validates :capacity, presence: true
  validates :duration, presence: true
  validates :price, presence: true

  mount_uploader :photo, PhotoUploader
end

app/models/mountain.rb
class Mountain < ApplicationRecord
  has_many :experiences
  validates :name, presence: true
  validates :city, presence: true

  mount_uploader :photo, PhotoUploader

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :experiences
  has_many :bookings

  validates :email, presence: true

  mount_uploader :photo, PhotoUploader

  def fullname
    "#{first_name.capitalize} #{last_name.capitalize}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  before_action :store_current_location, unless: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo, :bio])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo, :bio])
  end

  def store_current_location
      store_location_for(:user, request.url)
  end

  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || stored_location_for(resource) || root_url
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  before_action :set_experience, only: [:new, :create]

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.experience = @experience
    @booking.price = @experience.price
    if @booking.save
      redirect_to profile_path
    else
      render :new
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:date, :number_of_people)
  end

  def set_experience
    @experience = Experience.find(params[:experience_id])
  end
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_experience, only: [:show]

  def index
    if params[:query].present?
      @experiences = Experience.all.select { |experience| experience.mountain.city == params[:query] }.reverse
    else
      @experiences = Experience.all.reverse
    end
  end

  def new
    @experience = Experience.new
  end

  def show
    @booking = Booking.new
  end

  def create
    @experience = Experience.new(experience_params)
    @experience.user = current_user
    if @experience.save
      redirect_to profile_path(current_user)
    else
      render :new
    end
  end

  private

  def experience_params
    params.require(:experience).permit(:user, :name, :description, :capacity, :duration, :mountain_id, :price, :photo)
  end

  def set_experience
    @experience = Experience.find(params[:id])
  end
end

app/controllers/mountains_controller.rb
class MountainsController < ApplicationController

  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @mountains = Mountain.where.not(latitude: nil, longitude: nil)

    @markers = @mountains.map do |mountain|
      {
        lng: mountain.longitude,
        lat: mountain.latitude,
        infoWindow: render_to_string(partial: "infowindow", locals: { mountain: mountain })
      }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected
  def after_update_path_for(resource)
    profile_path(resource)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    # @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def photo_helper(obj)
    obj.photo.present? ? obj.photo : asset_url(obj.class::DEFAULT_PHOTO_URL)
  end

end

app/views/bookings/_form.html.erb
  <%= simple_form_for [@experience, @booking], html: { class: 'text-center input_label' } do |f|  %>
<<<<<<< HEAD
    <%= f.input :date, as: :date, input_html: {  class: 'text-center', type: 'date' }, html5: true %>
>>>>>>> master
    <%= f.input :number_of_people, input_html: { class: 'text-center' } %>
    <%= f.submit "Book now!", class: "btn btn-primary" %>
  <% end %>

app/views/bookings/new.html.erb
<div class="banner_exp" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @experience.photo, crop: :fill %>')">
  <h1 class="booking_title">Your Booking</h1>
  <div class="container" style="display:flex; align-items: center;">
    <div class="row">
      <div class="col-sm-4 col-sm-offset-4">
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/experiences/_form.html.erb
  <%= simple_form_for [@experience, @booking], html: { class: 'text-center input_label' } do |f|  %>
    <%= f.input :date, as: :string, placeholder: 'Select date...', input_html: {  class: 'datepicker text-center'}%>
    <%= f.input :number_of_people, input_html: { class: 'text-center' } %>
    <%= f.submit "Book now!", class: "btn btn-primary" %>
  <% end %>

app/views/experiences/index.html.erb
<div class="container" style="padding-bottom: 150px;">
  <div style="padding-top: 50px">
    <%= render 'components/search' %>
  </div>
  <h1 class="text-center" style="padding: 30px 0;">Experiences</h1>

  <div class="cards">
    <% @experiences.each do |experience| %>
      <%= link_to experience_path(experience) do %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path experience.photo, height: 300, width: 400, crop: :fill %>')">
          <%= experience.name %>
          <div class="card-description"><p><%= experience.mountain.name %> mountain</p></div>
          <div class="card-price"><h3>R$<%= experience.price %></h3></div>
        </div>
      <% end %>
    <% end %>

  </div>
</div>

app/views/experiences/new.html.erb
<h1 class="text-center">New Experience</h1>
<div class="container">
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">

      <%= simple_form_for @experience do |f| %>
        <%= f.input :name %>
        <%= f.association :mountain %>
        <%= f.input :description %>
        <%= f.input :capacity %>
        <%= f.input :duration %>
        <%= f.input :price, label: "Price per person" %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.button :submit %>
      <% end %>

    </div>
  </div>
</div>

app/views/experiences/show.html.erb
<h1 class="text-center" style="padding: 30px 0;"><%= @experience.name %></h1>

<%= cl_image_tag @experience.photo, transformation: { width: :auto, heigth: 500, crop: :fill }, class: "img-responsive center-block" %>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6">

      <div class="card-show card-guide">
        <div class="card-category-show"><strong>Climb Details:</strong></div>
        <div class="card-description-show">
          <p><%= @experience.description %></p>
          <h3><strong>Mountain:</strong> <%= @experience.mountain.name %></h3>
          <h3><strong>City:</strong> <%= @experience.mountain.city %></h3>
          <h3><strong>Max Participants:</strong> <%= @experience.capacity %></h3>
          <h3><strong>Duration:</strong> <%= @experience.duration %> hours</h3>
          <h3><strong>Price per person:</strong> R$ <%= @experience.price %></h3>
        </div>

      </div>
    </div>

    <div class="col-xs-12 col-sm-6">
      <div class="card-show card-guide">
        <img class="card-user-show" src="<%= @experience.user.photo.url %>">
        <div class="card-description-show">
          <h2><strong>Guide Name:</strong> <%= @experience.user.first_name %> <%= @experience.user.last_name %></h2>
          <p><%= @experience.user.bio %></p>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">
      <h3 class= "text-center" style="padding-top: 32px;">Book this experience:</h3>
      <div style="padding-top: 22px; padding-bottom: 96px;"><%= render "form" %></div>

    </div>
  </div>

</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>ClimbOn</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.53.1/mapbox-gl.css' rel='stylesheet' />
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'components/navbar' %>
    <%= render 'shared/flashes' %>
    <div style="min-height: calc(100vh - 70px - 100px); flex-direction: column; display: flex;">
      <%= yield %>
    </div>
    <%= render 'components/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/mountains/_infowindow.html.erb
<h2>Hello!</h2>

app/views/mountains/index.html.erb
<h1>Mountains#index</h1>
<p>Find me in app/views/mountains/index.html.erb</p>

<div
  id="map"
  style="width: 100%;
  height: 600px;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_path "climbing-rock-banner.jpg" %>')">
  <div class="banner-content">
    <h1>ClimbOn</h1>
    <p>Discover the best climbing experiences</p>
    <div class="wrap">
   <div class="search">
      <%= render 'components/search' %>
   </div>
</div>

    <!-- <a class="btn btn-primary btn-lg">Start now</a> -->
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="container">
<!-- <p><%#= current_user.email %></p> -->
<h1 style="text-align: center; padding: 30px 0;">Welcome <strong><%= current_user.first_name %>!</strong></h1>


<div class="container profile-container">
  <h3 class="text-center" style="padding-bottom: 20px;">Profile Info</h3>
  <div class="row">
    <div class="col-sm-12 col-lg-4">
      <%= cl_image_tag current_user.photo, height: 200, width: 200, crop: :fill, class: "avatar-square center-block" %>
      <br>
      <p><strong>E-mail: </strong><%= current_user.email %></p>
      <p><strong>Full Name: </strong><%= current_user.fullname %></p>
    </div>

    <div class="col-sm-12 col-lg-8 ">
      <p><strong>Biography: </strong><%= current_user.bio %></p>
      <br>
      <br>
      <div class="text-center"><%= link_to edit_user_registration_path do %>
        <button type="button" class="btn btn-success">Update Profile</button>
        <% end %>
      </div>
    </div>

  </div>
</div>

<div class="container profile-container">

  <h3 class="text-center">My offered experiences</h3>
  <div class="cards" style="padding: 30px 0">
    <% current_user.experiences.each do |experience| %>
      <%= link_to experience_path(experience) do %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path experience.photo, height: 300, width: 400, crop: :fill %>')">
          <%= experience.name %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="text-center"><%= link_to new_experience_path  do %>
        <button type="button" class="btn btn-success">
          <% if current_user.experiences.present? %>
            New Experience
          <% else %>
            Become a Guide!
          <% end %>
        </button>
      <% end %>
  </div>

</div>

<div class="container profile-container">

  <h3 class="text-center">My bookings</h3>
  <div class="cards" style="padding: 30px 0">
    <% current_user.bookings.each do |booking| %>
      <%= link_to experience_path(booking.experience) do %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path booking.experience.photo, height: 300, width: 400, crop: :fill %>')">
          <%= booking.experience.name %>
          <div class="date"><%= booking.date %></div>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="text-center"><%= link_to experiences_path  do %>
        <button type="button" class="btn btn-success">
          <% if current_user.bookings.present? %>
            New Booking
          <% else %>
            Book your first experience!
          <% end %>
        </button>
      <% end %>
  </div>

</div>